.PHONY: clean All

All:
	@echo "----------Building project:[ ejemplo05 - Debug ]----------"
	@cd "ejemplo05" && "$(MAKE)" -f  "ejemplo05.mk"
clean:
	@echo "----------Cleaning project:[ ejemplo05 - Debug ]----------"
	@cd "ejemplo05" && "$(MAKE)" -f  "ejemplo05.mk" clean
